FROM node:20-alpine AS base

# --- Dependencies ---
FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

# --- Build ---
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js bakes NEXT_PUBLIC_* at build time — pass via docker build-args
ARG NEXT_PUBLIC_CHAIN_ID=97
ARG NEXT_PUBLIC_RPC_URL
ARG NEXT_PUBLIC_AGENT_NFA
ARG NEXT_PUBLIC_LISTING_MANAGER
ARG NEXT_PUBLIC_POLICY_GUARD_V3
ARG NEXT_PUBLIC_DEPLOY_BLOCK
ARG NEXT_PUBLIC_ROUTER_ADDRESS
ARG NEXT_PUBLIC_POLICYGUARD_VERSION=v4
ARG NEXT_PUBLIC_EXPLORER_TX_BASE_URL
ARG NEXT_PUBLIC_INDEXER_URL
ARG NEXT_PUBLIC_RUNNER_URL
ARG NEXT_PUBLIC_RUNNER_OPERATOR
ARG NEXT_PUBLIC_OWNER_ADDRESS
ARG NEXT_PUBLIC_ADMIN_WALLET
ARG NEXT_PUBLIC_EXTRA_TOKENS

ENV NEXT_PUBLIC_CHAIN_ID=$NEXT_PUBLIC_CHAIN_ID \
    NEXT_PUBLIC_RPC_URL=$NEXT_PUBLIC_RPC_URL \
    NEXT_PUBLIC_AGENT_NFA=$NEXT_PUBLIC_AGENT_NFA \
    NEXT_PUBLIC_LISTING_MANAGER=$NEXT_PUBLIC_LISTING_MANAGER \
    NEXT_PUBLIC_POLICY_GUARD_V3=$NEXT_PUBLIC_POLICY_GUARD_V3 \
    NEXT_PUBLIC_DEPLOY_BLOCK=$NEXT_PUBLIC_DEPLOY_BLOCK \
    NEXT_PUBLIC_ROUTER_ADDRESS=$NEXT_PUBLIC_ROUTER_ADDRESS \
    NEXT_PUBLIC_POLICYGUARD_VERSION=$NEXT_PUBLIC_POLICYGUARD_VERSION \
    NEXT_PUBLIC_EXPLORER_TX_BASE_URL=$NEXT_PUBLIC_EXPLORER_TX_BASE_URL \
    NEXT_PUBLIC_INDEXER_URL=$NEXT_PUBLIC_INDEXER_URL \
    NEXT_PUBLIC_RUNNER_URL=$NEXT_PUBLIC_RUNNER_URL \
    NEXT_PUBLIC_RUNNER_OPERATOR=$NEXT_PUBLIC_RUNNER_OPERATOR \
    NEXT_PUBLIC_OWNER_ADDRESS=$NEXT_PUBLIC_OWNER_ADDRESS \
    NEXT_PUBLIC_ADMIN_WALLET=$NEXT_PUBLIC_ADMIN_WALLET \
    NEXT_PUBLIC_EXTRA_TOKENS=$NEXT_PUBLIC_EXTRA_TOKENS

RUN npm run build

# --- Production ---
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
